include "application.conf"

ktor {
  deployment {
    port = 8080
  }
}

app {
  database {
    url = "jdbc:postgresql://localhost:5432/smart_concierge"
    user = "postgres"
    password = "postgres"
  }
}