ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.smartconcierge.plugins.SerializationKt.configureSerialization
      com.smartconcierge.plugins.RoutingKt.configureRouting
      com.smartconcierge.ApplicationKt.module
    ]
  }
}


app {
  database {
    driver = "org.postgresql.Driver"
    driver = ${?DB_DRIVER}
    url = "jdbc:postgresql://localhost:5432/smart_concierge"
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = "postgres"
    password = ${?BD_PASSWORD}
  }
}