ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.smartconcierge.plugins.SerializationKt.configureSerialization
      com.smartconcierge.plugins.RoutingKt.configureRouting
      com.smartconcierge.ApplicationKt.module
    ]
  }
}

app {
  database {
    driver = "org.postgresql.Driver"
    driver = ${?DB_DRIVER}
  }
}