ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.smartconcierge.plugins.SerializationKt.configureSerialization
      com.smartconcierge.plugins.RoutingKt.configureRouting
      com.smartconcierge.ApplicationKt.module
    ]
  }
  database {
    url = "jdbc:postgresql://localhost:5432/smart_concierge"
    user = "postgres"
    password = "2181"
  }
}